# Example: AI-only local review config (skips static analysis tools)
# Usage: ai-review local --config .ai-review-local.yml --range main...HEAD .
# Requires: OPENAI_API_KEY environment variable

version: 1
trusted_only: false

provider: openai

passes:
  - name: cloud-ai
    agents: [opencode]
    enabled: true
    required: false

models:
  default: gpt-4.1

limits:
  max_files: 150
  max_diff_lines: 100000
  max_tokens_per_pr: 700000
  max_usd_per_pr: 50.00
  monthly_budget_usd: 500

gating:
  enabled: false
  fail_on_severity: error
